resources:
  repositories:
    - repository: templates
      type: github
      name: NSLS-II/profile-collection-ci
      ref: refs/heads/main
      endpoint: github

jobs:
  - template: collection-2021-1.0.yml@templates
    parameters:
      beamline_acronym: BMM
  - template: collection-2021-1.2.yml@templates
    parameters:
      beamline_acronym: BMM

